# Generated by Django 2.2.6 on 2021-01-20 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cat_Name', models.CharField(max_length=60)),
                ('Cat_Description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Recipe_Title', models.CharField(max_length=60)),
                ('Recipe_Ingredients', models.TextField()),
                ('Recipe_Description', models.TextField()),
                ('Recipe_Info', models.TextField()),
                ('Recipe_Cat', models.IntegerField(choices=[(1, 'Snídaně a svačiny'), (2, 'Obědy a večeře'), (3, 'Zdravé mlsání'), (4, 'Polévky'), (5, 'Saláty a přílohy'), (6, 'Nápoje')], default=1)),
                ('Recipe_Img', models.ImageField(blank=True, upload_to='../recepty/img')),
                ('Recipe_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Recipe_note', models.TextField(blank=True)),
                ('Recipe_Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prispevek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('datum_vytvoreni', models.DateTimeField(default=django.utils.timezone.now)),
                ('datum_publikace', models.DateTimeField(blank=True, null=True)),
                ('tvurce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
