# Generated by Django 2.2.6 on 2021-01-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='Recipe_Img',
            field=models.ImageField(blank=True, upload_to='../recepty'),
        ),
    ]
