# Generated by Django 2.2.6 on 2021-01-20 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210120_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='Recipe_Cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Cat'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Recipe_Img',
            field=models.ImageField(blank=True, upload_to='../media'),
        ),
    ]
